# coding: utf-8

"""
    Kadastraal onroerende zaken

    D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class KadasterNietNatuurlijkPersoonHalCollectieEmbedded(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kadaster_niet_natuurlijk_personen': 'list[KadasterNietNatuurlijkPersoonHal]'
    }

    attribute_map = {
        'kadaster_niet_natuurlijk_personen': 'kadasterNietNatuurlijkPersonen'
    }

    def __init__(self, kadaster_niet_natuurlijk_personen=None):  # noqa: E501
        """KadasterNietNatuurlijkPersoonHalCollectieEmbedded - a model defined in Swagger"""  # noqa: E501
        self._kadaster_niet_natuurlijk_personen = None
        self.discriminator = None
        if kadaster_niet_natuurlijk_personen is not None:
            self.kadaster_niet_natuurlijk_personen = kadaster_niet_natuurlijk_personen

    @property
    def kadaster_niet_natuurlijk_personen(self):
        """Gets the kadaster_niet_natuurlijk_personen of this KadasterNietNatuurlijkPersoonHalCollectieEmbedded.  # noqa: E501


        :return: The kadaster_niet_natuurlijk_personen of this KadasterNietNatuurlijkPersoonHalCollectieEmbedded.  # noqa: E501
        :rtype: list[KadasterNietNatuurlijkPersoonHal]
        """
        return self._kadaster_niet_natuurlijk_personen

    @kadaster_niet_natuurlijk_personen.setter
    def kadaster_niet_natuurlijk_personen(self, kadaster_niet_natuurlijk_personen):
        """Sets the kadaster_niet_natuurlijk_personen of this KadasterNietNatuurlijkPersoonHalCollectieEmbedded.


        :param kadaster_niet_natuurlijk_personen: The kadaster_niet_natuurlijk_personen of this KadasterNietNatuurlijkPersoonHalCollectieEmbedded.  # noqa: E501
        :type: list[KadasterNietNatuurlijkPersoonHal]
        """

        self._kadaster_niet_natuurlijk_personen = kadaster_niet_natuurlijk_personen

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KadasterNietNatuurlijkPersoonHalCollectieEmbedded, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KadasterNietNatuurlijkPersoonHalCollectieEmbedded):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
