# coding: utf-8

"""
    Kadastraal onroerende zaken

    D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.persoon_beperkt import PersoonBeperkt  # noqa: E501
from swagger_client.rest import ApiException


class TestPersoonBeperkt(unittest.TestCase):
    """PersoonBeperkt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersoonBeperkt(self):
        """Test PersoonBeperkt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.persoon_beperkt.PersoonBeperkt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
