/*
 * Kadaster - BRK-Bevragen API
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AppartementsrechtBasis;
import org.openapitools.client.model.AppartementsrechtHal;
import org.openapitools.client.model.Filiatie;
import org.openapitools.client.model.KadastraalOnroerendeZaakEmbedded;
import org.openapitools.client.model.KadastraalOnroerendeZaakHal;
import org.openapitools.client.model.LocatieKadastraalObject;
import org.openapitools.client.model.PerceelHal;
import org.openapitools.client.model.PerceelHalAllOf;
import org.openapitools.client.model.PerceelLinks;
import org.openapitools.client.model.PointGeoJSON;
import org.openapitools.client.model.PolygonGeoJSON;
import org.openapitools.client.model.TypeKadastraalOnroerendeZaakEnum;
import org.openapitools.client.model.TypeKoopsom;
import org.openapitools.client.model.TypeOppervlak;
import org.openapitools.client.model.TypePerceelnummerVerschuiving;
import org.openapitools.client.model.Waardelijst;

/**
 * PerceelHal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-14T09:58:19.624161Z[Etc/UTC]")
public class PerceelHal extends KadastraalOnroerendeZaakHal {
  public static final String SERIALIZED_NAME_INDICATIE_VERVALLEN = "indicatieVervallen";
  @SerializedName(SERIALIZED_NAME_INDICATIE_VERVALLEN)
  private Boolean indicatieVervallen;

  public static final String SERIALIZED_NAME_BIJBEHORENDE_APPARTEMENTSRECHTEN = "bijbehorendeAppartementsrechten";
  @SerializedName(SERIALIZED_NAME_BIJBEHORENDE_APPARTEMENTSRECHTEN)
  private AppartementsrechtBasis bijbehorendeAppartementsrechten;

  public static final String SERIALIZED_NAME_BEGRENZING = "begrenzing";
  @SerializedName(SERIALIZED_NAME_BEGRENZING)
  private PolygonGeoJSON begrenzing;

  public static final String SERIALIZED_NAME_PLAATSCOORDINATEN = "plaatscoordinaten";
  @SerializedName(SERIALIZED_NAME_PLAATSCOORDINATEN)
  private PointGeoJSON plaatscoordinaten;

  public static final String SERIALIZED_NAME_KADASTRALE_GROOTTE = "kadastraleGrootte";
  @SerializedName(SERIALIZED_NAME_KADASTRALE_GROOTTE)
  private TypeOppervlak kadastraleGrootte;

  public static final String SERIALIZED_NAME_PERCEELNUMMER_VERSCHUIVING = "perceelnummerVerschuiving";
  @SerializedName(SERIALIZED_NAME_PERCEELNUMMER_VERSCHUIVING)
  private TypePerceelnummerVerschuiving perceelnummerVerschuiving;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private PerceelLinks links;

  public PerceelHal() {
    this.type = this.getClass().getSimpleName();
  }

  public PerceelHal indicatieVervallen(Boolean indicatieVervallen) {
    
    this.indicatieVervallen = indicatieVervallen;
    return this;
  }

   /**
   * Get indicatieVervallen
   * @return indicatieVervallen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIndicatieVervallen() {
    return indicatieVervallen;
  }


  public void setIndicatieVervallen(Boolean indicatieVervallen) {
    this.indicatieVervallen = indicatieVervallen;
  }


  public PerceelHal bijbehorendeAppartementsrechten(AppartementsrechtBasis bijbehorendeAppartementsrechten) {
    
    this.bijbehorendeAppartementsrechten = bijbehorendeAppartementsrechten;
    return this;
  }

   /**
   * Get bijbehorendeAppartementsrechten
   * @return bijbehorendeAppartementsrechten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AppartementsrechtBasis getBijbehorendeAppartementsrechten() {
    return bijbehorendeAppartementsrechten;
  }


  public void setBijbehorendeAppartementsrechten(AppartementsrechtBasis bijbehorendeAppartementsrechten) {
    this.bijbehorendeAppartementsrechten = bijbehorendeAppartementsrechten;
  }


  public PerceelHal begrenzing(PolygonGeoJSON begrenzing) {
    
    this.begrenzing = begrenzing;
    return this;
  }

   /**
   * Get begrenzing
   * @return begrenzing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PolygonGeoJSON getBegrenzing() {
    return begrenzing;
  }


  public void setBegrenzing(PolygonGeoJSON begrenzing) {
    this.begrenzing = begrenzing;
  }


  public PerceelHal plaatscoordinaten(PointGeoJSON plaatscoordinaten) {
    
    this.plaatscoordinaten = plaatscoordinaten;
    return this;
  }

   /**
   * Get plaatscoordinaten
   * @return plaatscoordinaten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PointGeoJSON getPlaatscoordinaten() {
    return plaatscoordinaten;
  }


  public void setPlaatscoordinaten(PointGeoJSON plaatscoordinaten) {
    this.plaatscoordinaten = plaatscoordinaten;
  }


  public PerceelHal kadastraleGrootte(TypeOppervlak kadastraleGrootte) {
    
    this.kadastraleGrootte = kadastraleGrootte;
    return this;
  }

   /**
   * Get kadastraleGrootte
   * @return kadastraleGrootte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TypeOppervlak getKadastraleGrootte() {
    return kadastraleGrootte;
  }


  public void setKadastraleGrootte(TypeOppervlak kadastraleGrootte) {
    this.kadastraleGrootte = kadastraleGrootte;
  }


  public PerceelHal perceelnummerVerschuiving(TypePerceelnummerVerschuiving perceelnummerVerschuiving) {
    
    this.perceelnummerVerschuiving = perceelnummerVerschuiving;
    return this;
  }

   /**
   * Get perceelnummerVerschuiving
   * @return perceelnummerVerschuiving
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TypePerceelnummerVerschuiving getPerceelnummerVerschuiving() {
    return perceelnummerVerschuiving;
  }


  public void setPerceelnummerVerschuiving(TypePerceelnummerVerschuiving perceelnummerVerschuiving) {
    this.perceelnummerVerschuiving = perceelnummerVerschuiving;
  }


  public PerceelHal links(PerceelLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PerceelLinks getLinks() {
    return links;
  }


  public void setLinks(PerceelLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerceelHal perceelHal = (PerceelHal) o;
    return Objects.equals(this.indicatieVervallen, perceelHal.indicatieVervallen) &&
        Objects.equals(this.bijbehorendeAppartementsrechten, perceelHal.bijbehorendeAppartementsrechten) &&
        Objects.equals(this.begrenzing, perceelHal.begrenzing) &&
        Objects.equals(this.plaatscoordinaten, perceelHal.plaatscoordinaten) &&
        Objects.equals(this.kadastraleGrootte, perceelHal.kadastraleGrootte) &&
        Objects.equals(this.perceelnummerVerschuiving, perceelHal.perceelnummerVerschuiving) &&
        Objects.equals(this.links, perceelHal.links) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indicatieVervallen, bijbehorendeAppartementsrechten, begrenzing, plaatscoordinaten, kadastraleGrootte, perceelnummerVerschuiving, links, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerceelHal {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    indicatieVervallen: ").append(toIndentedString(indicatieVervallen)).append("\n");
    sb.append("    bijbehorendeAppartementsrechten: ").append(toIndentedString(bijbehorendeAppartementsrechten)).append("\n");
    sb.append("    begrenzing: ").append(toIndentedString(begrenzing)).append("\n");
    sb.append("    plaatscoordinaten: ").append(toIndentedString(plaatscoordinaten)).append("\n");
    sb.append("    kadastraleGrootte: ").append(toIndentedString(kadastraleGrootte)).append("\n");
    sb.append("    perceelnummerVerschuiving: ").append(toIndentedString(perceelnummerVerschuiving)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

