/*
 * Kadastraal onroerende zaken
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Adres;
import org.openapitools.client.model.PostadresAllOf;
import org.openapitools.client.model.Waardelijst;

/**
 * Postadres
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-02T17:36:04.072+02:00[Europe/Amsterdam]")
public class Postadres extends Adres {
  public static final String SERIALIZED_NAME_POSTBUSNUMMER = "postbusnummer";
  @SerializedName(SERIALIZED_NAME_POSTBUSNUMMER)
  private Integer postbusnummer;


  public Postadres postbusnummer(Integer postbusnummer) {
    
    this.postbusnummer = postbusnummer;
    return this;
  }

   /**
   * Get postbusnummer
   * @return postbusnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPostbusnummer() {
    return postbusnummer;
  }


  public void setPostbusnummer(Integer postbusnummer) {
    this.postbusnummer = postbusnummer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Postadres postadres = (Postadres) o;
    return Objects.equals(this.postbusnummer, postadres.postbusnummer) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postbusnummer, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Postadres {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    postbusnummer: ").append(toIndentedString(postbusnummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

