/*
 * Kadaster - BRK-Bevragen API
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ErfpachtCanon;
import org.openapitools.client.model.PersoonBeperkt;
import org.openapitools.client.model.Tenaamstelling;
import org.openapitools.client.model.TypeGerechtigdeEnum;

/**
 * ZakelijkGerechtigde
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-20T16:12:03.834Z[Etc/UTC]")
public class ZakelijkGerechtigde {
  public static final String SERIALIZED_NAME_IDENTIFICATIE = "identificatie";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE)
  private String identificatie;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeGerechtigdeEnum type;

  public static final String SERIALIZED_NAME_AANVANGSDATUM = "aanvangsdatum";
  @SerializedName(SERIALIZED_NAME_AANVANGSDATUM)
  private LocalDate aanvangsdatum;

  public static final String SERIALIZED_NAME_ERFPACHT_CANON = "erfpachtCanon";
  @SerializedName(SERIALIZED_NAME_ERFPACHT_CANON)
  private ErfpachtCanon erfpachtCanon;

  public static final String SERIALIZED_NAME_TENAAMSTELLING = "tenaamstelling";
  @SerializedName(SERIALIZED_NAME_TENAAMSTELLING)
  private Tenaamstelling tenaamstelling;

  public static final String SERIALIZED_NAME_PERSOON = "persoon";
  @SerializedName(SERIALIZED_NAME_PERSOON)
  private PersoonBeperkt persoon = null;

  public static final String SERIALIZED_NAME_STUK_IDENTIFICATIES = "stukIdentificaties";
  @SerializedName(SERIALIZED_NAME_STUK_IDENTIFICATIES)
  private List<String> stukIdentificaties = null;

  public static final String SERIALIZED_NAME_IS_GEBASEERD_OP_STUKDEEL_IDENTIFICATIE = "isGebaseerdOpStukdeelIdentificatie";
  @SerializedName(SERIALIZED_NAME_IS_GEBASEERD_OP_STUKDEEL_IDENTIFICATIE)
  private String isGebaseerdOpStukdeelIdentificatie;

  public static final String SERIALIZED_NAME_IS_VERMELD_IN_STUKDEEL_IDENTIFICATIES = "isVermeldInStukdeelIdentificaties";
  @SerializedName(SERIALIZED_NAME_IS_VERMELD_IN_STUKDEEL_IDENTIFICATIES)
  private List<String> isVermeldInStukdeelIdentificaties = null;


  public ZakelijkGerechtigde identificatie(String identificatie) {
    
    this.identificatie = identificatie;
    return this;
  }

   /**
   * Identificatie van de zakelijk gerechtigde. 
   * @return identificatie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identificatie van de zakelijk gerechtigde. ")

  public String getIdentificatie() {
    return identificatie;
  }


  public void setIdentificatie(String identificatie) {
    this.identificatie = identificatie;
  }


  public ZakelijkGerechtigde type(TypeGerechtigdeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TypeGerechtigdeEnum getType() {
    return type;
  }


  public void setType(TypeGerechtigdeEnum type) {
    this.type = type;
  }


  public ZakelijkGerechtigde aanvangsdatum(LocalDate aanvangsdatum) {
    
    this.aanvangsdatum = aanvangsdatum;
    return this;
  }

   /**
   * Datum waarop het zakelijk recht van kracht is geworden. 
   * @return aanvangsdatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum waarop het zakelijk recht van kracht is geworden. ")

  public LocalDate getAanvangsdatum() {
    return aanvangsdatum;
  }


  public void setAanvangsdatum(LocalDate aanvangsdatum) {
    this.aanvangsdatum = aanvangsdatum;
  }


  public ZakelijkGerechtigde erfpachtCanon(ErfpachtCanon erfpachtCanon) {
    
    this.erfpachtCanon = erfpachtCanon;
    return this;
  }

   /**
   * Get erfpachtCanon
   * @return erfpachtCanon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ErfpachtCanon getErfpachtCanon() {
    return erfpachtCanon;
  }


  public void setErfpachtCanon(ErfpachtCanon erfpachtCanon) {
    this.erfpachtCanon = erfpachtCanon;
  }


  public ZakelijkGerechtigde tenaamstelling(Tenaamstelling tenaamstelling) {
    
    this.tenaamstelling = tenaamstelling;
    return this;
  }

   /**
   * Get tenaamstelling
   * @return tenaamstelling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Tenaamstelling getTenaamstelling() {
    return tenaamstelling;
  }


  public void setTenaamstelling(Tenaamstelling tenaamstelling) {
    this.tenaamstelling = tenaamstelling;
  }


  public ZakelijkGerechtigde persoon(PersoonBeperkt persoon) {
    
    this.persoon = persoon;
    return this;
  }

   /**
   * Get persoon
   * @return persoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersoonBeperkt getPersoon() {
    return persoon;
  }


  public void setPersoon(PersoonBeperkt persoon) {
    this.persoon = persoon;
  }


  public ZakelijkGerechtigde stukIdentificaties(List<String> stukIdentificaties) {
    
    this.stukIdentificaties = stukIdentificaties;
    return this;
  }

  public ZakelijkGerechtigde addStukIdentificatiesItem(String stukIdentificatiesItem) {
    if (this.stukIdentificaties == null) {
      this.stukIdentificaties = new ArrayList<>();
    }
    this.stukIdentificaties.add(stukIdentificatiesItem);
    return this;
  }

   /**
   * Dit element is de identificatie van het Stuk. Dit kan een aangeboden Stuk of een Kadasterstuk zijn. 
   * @return stukIdentificaties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Dit element is de identificatie van het Stuk. Dit kan een aangeboden Stuk of een Kadasterstuk zijn. ")

  public List<String> getStukIdentificaties() {
    return stukIdentificaties;
  }


  public void setStukIdentificaties(List<String> stukIdentificaties) {
    this.stukIdentificaties = stukIdentificaties;
  }


  public ZakelijkGerechtigde isGebaseerdOpStukdeelIdentificatie(String isGebaseerdOpStukdeelIdentificatie) {
    
    this.isGebaseerdOpStukdeelIdentificatie = isGebaseerdOpStukdeelIdentificatie;
    return this;
  }

   /**
   * De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop dit zakelijk recht is gebaseerd. 
   * @return isGebaseerdOpStukdeelIdentificatie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop dit zakelijk recht is gebaseerd. ")

  public String getIsGebaseerdOpStukdeelIdentificatie() {
    return isGebaseerdOpStukdeelIdentificatie;
  }


  public void setIsGebaseerdOpStukdeelIdentificatie(String isGebaseerdOpStukdeelIdentificatie) {
    this.isGebaseerdOpStukdeelIdentificatie = isGebaseerdOpStukdeelIdentificatie;
  }


  public ZakelijkGerechtigde isVermeldInStukdeelIdentificaties(List<String> isVermeldInStukdeelIdentificaties) {
    
    this.isVermeldInStukdeelIdentificaties = isVermeldInStukdeelIdentificaties;
    return this;
  }

  public ZakelijkGerechtigde addIsVermeldInStukdeelIdentificatiesItem(String isVermeldInStukdeelIdentificatiesItem) {
    if (this.isVermeldInStukdeelIdentificaties == null) {
      this.isVermeldInStukdeelIdentificaties = new ArrayList<>();
    }
    this.isVermeldInStukdeelIdentificaties.add(isVermeldInStukdeelIdentificatiesItem);
    return this;
  }

   /**
   * De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarin deze zakelijk gerechtigde is vermeld. 
   * @return isVermeldInStukdeelIdentificaties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarin deze zakelijk gerechtigde is vermeld. ")

  public List<String> getIsVermeldInStukdeelIdentificaties() {
    return isVermeldInStukdeelIdentificaties;
  }


  public void setIsVermeldInStukdeelIdentificaties(List<String> isVermeldInStukdeelIdentificaties) {
    this.isVermeldInStukdeelIdentificaties = isVermeldInStukdeelIdentificaties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZakelijkGerechtigde zakelijkGerechtigde = (ZakelijkGerechtigde) o;
    return Objects.equals(this.identificatie, zakelijkGerechtigde.identificatie) &&
        Objects.equals(this.type, zakelijkGerechtigde.type) &&
        Objects.equals(this.aanvangsdatum, zakelijkGerechtigde.aanvangsdatum) &&
        Objects.equals(this.erfpachtCanon, zakelijkGerechtigde.erfpachtCanon) &&
        Objects.equals(this.tenaamstelling, zakelijkGerechtigde.tenaamstelling) &&
        Objects.equals(this.persoon, zakelijkGerechtigde.persoon) &&
        Objects.equals(this.stukIdentificaties, zakelijkGerechtigde.stukIdentificaties) &&
        Objects.equals(this.isGebaseerdOpStukdeelIdentificatie, zakelijkGerechtigde.isGebaseerdOpStukdeelIdentificatie) &&
        Objects.equals(this.isVermeldInStukdeelIdentificaties, zakelijkGerechtigde.isVermeldInStukdeelIdentificaties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificatie, type, aanvangsdatum, erfpachtCanon, tenaamstelling, persoon, stukIdentificaties, isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZakelijkGerechtigde {\n");
    sb.append("    identificatie: ").append(toIndentedString(identificatie)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    aanvangsdatum: ").append(toIndentedString(aanvangsdatum)).append("\n");
    sb.append("    erfpachtCanon: ").append(toIndentedString(erfpachtCanon)).append("\n");
    sb.append("    tenaamstelling: ").append(toIndentedString(tenaamstelling)).append("\n");
    sb.append("    persoon: ").append(toIndentedString(persoon)).append("\n");
    sb.append("    stukIdentificaties: ").append(toIndentedString(stukIdentificaties)).append("\n");
    sb.append("    isGebaseerdOpStukdeelIdentificatie: ").append(toIndentedString(isGebaseerdOpStukdeelIdentificatie)).append("\n");
    sb.append("    isVermeldInStukdeelIdentificaties: ").append(toIndentedString(isVermeldInStukdeelIdentificaties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

