/* 
 * Kadastraal onroerende zaken
 *
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ZakelijkGerechtigdeLinks
    /// </summary>
    [DataContract]
    public partial class ZakelijkGerechtigdeLinks :  IEquatable<ZakelijkGerechtigdeLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZakelijkGerechtigdeLinks" /> class.
        /// </summary>
        /// <param name="self">self.</param>
        /// <param name="persoon">persoon.</param>
        /// <param name="betrokkenPartner">betrokkenPartner.</param>
        /// <param name="betrokkenSamenwerkingsverband">betrokkenSamenwerkingsverband.</param>
        /// <param name="betrokkenGorzenEnAanwassen">betrokkenGorzenEnAanwassen.</param>
        public ZakelijkGerechtigdeLinks(HalLink self = default(HalLink), HalLink persoon = default(HalLink), HalLink betrokkenPartner = default(HalLink), HalLink betrokkenSamenwerkingsverband = default(HalLink), HalLink betrokkenGorzenEnAanwassen = default(HalLink))
        {
            this.Self = self;
            this.Persoon = persoon;
            this.BetrokkenPartner = betrokkenPartner;
            this.BetrokkenSamenwerkingsverband = betrokkenSamenwerkingsverband;
            this.BetrokkenGorzenEnAanwassen = betrokkenGorzenEnAanwassen;
        }
        
        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=false)]
        public HalLink Self { get; set; }

        /// <summary>
        /// Gets or Sets Persoon
        /// </summary>
        [DataMember(Name="persoon", EmitDefaultValue=false)]
        public HalLink Persoon { get; set; }

        /// <summary>
        /// Gets or Sets BetrokkenPartner
        /// </summary>
        [DataMember(Name="betrokkenPartner", EmitDefaultValue=false)]
        public HalLink BetrokkenPartner { get; set; }

        /// <summary>
        /// Gets or Sets BetrokkenSamenwerkingsverband
        /// </summary>
        [DataMember(Name="betrokkenSamenwerkingsverband", EmitDefaultValue=false)]
        public HalLink BetrokkenSamenwerkingsverband { get; set; }

        /// <summary>
        /// Gets or Sets BetrokkenGorzenEnAanwassen
        /// </summary>
        [DataMember(Name="betrokkenGorzenEnAanwassen", EmitDefaultValue=false)]
        public HalLink BetrokkenGorzenEnAanwassen { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ZakelijkGerechtigdeLinks {\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  Persoon: ").Append(Persoon).Append("\n");
            sb.Append("  BetrokkenPartner: ").Append(BetrokkenPartner).Append("\n");
            sb.Append("  BetrokkenSamenwerkingsverband: ").Append(BetrokkenSamenwerkingsverband).Append("\n");
            sb.Append("  BetrokkenGorzenEnAanwassen: ").Append(BetrokkenGorzenEnAanwassen).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ZakelijkGerechtigdeLinks);
        }

        /// <summary>
        /// Returns true if ZakelijkGerechtigdeLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of ZakelijkGerechtigdeLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ZakelijkGerechtigdeLinks input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Self == input.Self ||
                    (this.Self != null &&
                    this.Self.Equals(input.Self))
                ) && 
                (
                    this.Persoon == input.Persoon ||
                    (this.Persoon != null &&
                    this.Persoon.Equals(input.Persoon))
                ) && 
                (
                    this.BetrokkenPartner == input.BetrokkenPartner ||
                    (this.BetrokkenPartner != null &&
                    this.BetrokkenPartner.Equals(input.BetrokkenPartner))
                ) && 
                (
                    this.BetrokkenSamenwerkingsverband == input.BetrokkenSamenwerkingsverband ||
                    (this.BetrokkenSamenwerkingsverband != null &&
                    this.BetrokkenSamenwerkingsverband.Equals(input.BetrokkenSamenwerkingsverband))
                ) && 
                (
                    this.BetrokkenGorzenEnAanwassen == input.BetrokkenGorzenEnAanwassen ||
                    (this.BetrokkenGorzenEnAanwassen != null &&
                    this.BetrokkenGorzenEnAanwassen.Equals(input.BetrokkenGorzenEnAanwassen))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Self != null)
                    hashCode = hashCode * 59 + this.Self.GetHashCode();
                if (this.Persoon != null)
                    hashCode = hashCode * 59 + this.Persoon.GetHashCode();
                if (this.BetrokkenPartner != null)
                    hashCode = hashCode * 59 + this.BetrokkenPartner.GetHashCode();
                if (this.BetrokkenSamenwerkingsverband != null)
                    hashCode = hashCode * 59 + this.BetrokkenSamenwerkingsverband.GetHashCode();
                if (this.BetrokkenGorzenEnAanwassen != null)
                    hashCode = hashCode * 59 + this.BetrokkenGorzenEnAanwassen.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
