/*
 * Kadastraal onroerende zaken
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DatumOnvolledig;
import org.openapitools.client.model.Naam;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HeeftPartnerschap
 */
public class HeeftPartnerschapTest {
    private final HeeftPartnerschap model = new HeeftPartnerschap();

    /**
     * Model tests for HeeftPartnerschap
     */
    @Test
    public void testHeeftPartnerschap() {
        // TODO: test HeeftPartnerschap
    }

    /**
     * Test the property 'datumOntbinding'
     */
    @Test
    public void datumOntbindingTest() {
        // TODO: test datumOntbinding
    }

    /**
     * Test the property 'datumSluiting'
     */
    @Test
    public void datumSluitingTest() {
        // TODO: test datumSluiting
    }

    /**
     * Test the property 'naam'
     */
    @Test
    public void naamTest() {
        // TODO: test naam
    }

}
