/*
 * Kadastraal onroerende zaken
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Adres;
import org.openapitools.client.model.KadasterNietNatuurlijkPersoon;
import org.openapitools.client.model.KadasterPersoonLinks;
import org.openapitools.client.model.Postadres;
import org.openapitools.client.model.Waardelijst;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KadasterNietNatuurlijkPersoonHal
 */
public class KadasterNietNatuurlijkPersoonHalTest {
    private final KadasterNietNatuurlijkPersoonHal model = new KadasterNietNatuurlijkPersoonHal();

    /**
     * Model tests for KadasterNietNatuurlijkPersoonHal
     */
    @Test
    public void testKadasterNietNatuurlijkPersoonHal() {
        // TODO: test KadasterNietNatuurlijkPersoonHal
    }

    /**
     * Test the property 'identificatie'
     */
    @Test
    public void identificatieTest() {
        // TODO: test identificatie
    }

    /**
     * Test the property 'omschrijving'
     */
    @Test
    public void omschrijvingTest() {
        // TODO: test omschrijving
    }

    /**
     * Test the property 'domein'
     */
    @Test
    public void domeinTest() {
        // TODO: test domein
    }

    /**
     * Test the property 'indicatieNietToonbareDiakriet'
     */
    @Test
    public void indicatieNietToonbareDiakrietTest() {
        // TODO: test indicatieNietToonbareDiakriet
    }

    /**
     * Test the property 'beschikkingsbevoegdheid'
     */
    @Test
    public void beschikkingsbevoegdheidTest() {
        // TODO: test beschikkingsbevoegdheid
    }

    /**
     * Test the property 'woonadres'
     */
    @Test
    public void woonadresTest() {
        // TODO: test woonadres
    }

    /**
     * Test the property 'postadres'
     */
    @Test
    public void postadresTest() {
        // TODO: test postadres
    }

    /**
     * Test the property 'kadastraalOnroerendeZaakIdentificaties'
     */
    @Test
    public void kadastraalOnroerendeZaakIdentificatiesTest() {
        // TODO: test kadastraalOnroerendeZaakIdentificaties
    }

    /**
     * Test the property 'statutaireNaam'
     */
    @Test
    public void statutaireNaamTest() {
        // TODO: test statutaireNaam
    }

    /**
     * Test the property 'statutaireZetel'
     */
    @Test
    public void statutaireZetelTest() {
        // TODO: test statutaireZetel
    }

    /**
     * Test the property 'rechtsvorm'
     */
    @Test
    public void rechtsvormTest() {
        // TODO: test rechtsvorm
    }

    /**
     * Test the property 'kvkNummer'
     */
    @Test
    public void kvkNummerTest() {
        // TODO: test kvkNummer
    }

    /**
     * Test the property 'rsin'
     */
    @Test
    public void rsinTest() {
        // TODO: test rsin
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
