/*
 * Kadastraal onroerende zaken
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.HalLink;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KadasterPersoonLinks
 */
public class KadasterPersoonLinksTest {
    private final KadasterPersoonLinks model = new KadasterPersoonLinks();

    /**
     * Model tests for KadasterPersoonLinks
     */
    @Test
    public void testKadasterPersoonLinks() {
        // TODO: test KadasterPersoonLinks
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'woonadres'
     */
    @Test
    public void woonadresTest() {
        // TODO: test woonadres
    }

    /**
     * Test the property 'postadres'
     */
    @Test
    public void postadresTest() {
        // TODO: test postadres
    }

    /**
     * Test the property 'kadastraalOnroerendeZaken'
     */
    @Test
    public void kadastraalOnroerendeZakenTest() {
        // TODO: test kadastraalOnroerendeZaken
    }

    /**
     * Test the property 'zakelijkGerechtigden'
     */
    @Test
    public void zakelijkGerechtigdenTest() {
        // TODO: test zakelijkGerechtigden
    }

}
