/*
 * Kadastraal onroerende zaken
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.client.model.ErfpachtCanon;
import org.openapitools.client.model.PersoonBeperkt;
import org.openapitools.client.model.Tenaamstelling;
import org.openapitools.client.model.TypeGerechtigdeEnum;
import org.openapitools.client.model.ZakelijkGerechtigde;
import org.openapitools.client.model.ZakelijkGerechtigdeLinks;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ZakelijkGerechtigdeHal
 */
public class ZakelijkGerechtigdeHalTest {
    private final ZakelijkGerechtigdeHal model = new ZakelijkGerechtigdeHal();

    /**
     * Model tests for ZakelijkGerechtigdeHal
     */
    @Test
    public void testZakelijkGerechtigdeHal() {
        // TODO: test ZakelijkGerechtigdeHal
    }

    /**
     * Test the property 'identificatie'
     */
    @Test
    public void identificatieTest() {
        // TODO: test identificatie
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'aanvangsdatum'
     */
    @Test
    public void aanvangsdatumTest() {
        // TODO: test aanvangsdatum
    }

    /**
     * Test the property 'erfpachtCanon'
     */
    @Test
    public void erfpachtCanonTest() {
        // TODO: test erfpachtCanon
    }

    /**
     * Test the property 'tenaamstelling'
     */
    @Test
    public void tenaamstellingTest() {
        // TODO: test tenaamstelling
    }

    /**
     * Test the property 'persoon'
     */
    @Test
    public void persoonTest() {
        // TODO: test persoon
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
