openapi: 3.0.0
info:
  title: Kadaster - BRK-Bevragen API - Kadaster Niet Natuurlijk Personen endpoints
  description: |
                De definitie van de Kadaster Niet Natuurlijk Personen endpoints en HAL components.
  version: "1.5.0"
paths:
  /kadasternietnatuurlijkpersonen/{kadasterNietNatuurlijkPersoonIdentificatie}:
    get:
      operationId: GetKadasterNietNatuurlijkPersoon
      description: |
                    Raadpleeg een bij het kadaster geregistreerde niet natuurlijke persoon die niet in het Handelsregister (HR) is
                    ingeschreven, of wel is ingeschreven maar niet is gekoppeld bij het inschrijven van de akte.
                    Kadasternatuurlijkpersonen worden niet geactualiseerd.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/parameters/fields"
        - in: path
          name: kadasterNietNatuurlijkPersoonIdentificatie
          required: true
          schema:
            type: string
            maxLength: 60
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadasterNietNatuurlijkPersoonHal'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/406"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Kadaster (niet)Natuurlijk Personen
  /kadasternietnatuurlijkpersonen:
    get:
      operationId: GetKadasterNietNatuurlijkPersonen
      description: |
                    Zoek bij het kadaster geregistreerde niet natuurlijke personen die niet in het Handelsregister (HR) zijn ingeschreven,
                    of wel zijn ingeschreven maar niet gekoppeld bij het inschrijven van de akte.
                    Kadasternatuurlijkpersonen worden niet geactualiseerd.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/parameters/fields"
        - in: query
          name: q
          description: |
                        Free query parameter. Dit endpoint evolueert naar free query zoeken. In deze versie kan alleen een combinatie van (het begin van de) de statutaire naam en zetel (vestigingsplaats) worden opgegeven. Let op! Een niet natuurlijk persoon kan meerdere keren, en op meer dan één manier voorkomen in de BRK.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadasterNietNatuurlijkPersoonHalCollectie'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/406"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Kadaster (niet)Natuurlijk Personen
components:
  schemas:
    KadasterNietNatuurlijkPersoonHal:
      allOf:
      - $ref: "domain.yaml#/components/schemas/KadasterNietNatuurlijkPersoon"
      - properties:
          _links:
            $ref: "kadaster-natuurlijk-personen.yaml#/components/schemas/KadasterPersoonLinks"
    KadasterNietNatuurlijkPersoonHalCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        _embedded:
          $ref: "#/components/schemas/KadasterNietNatuurlijkPersoonHalCollectieEmbedded"
    KadasterNietNatuurlijkPersoonHalCollectieEmbedded:
      type: "object"
      properties:
        kadasterNietNatuurlijkPersonen:
          type: "array"
          items:
            $ref: "#/components/schemas/KadasterNietNatuurlijkPersoonHal"
