openapi: 3.0.0
info:
  title: Kadaster - BRK-Bevragen API - Publiek rechtelijke beperkingen endpoints
  description: |
                De definitie van de Publiek rechtelijke beperkingen endpoints en components.
  version: "1.5.0"
paths:
  /publiekrechtelijkebeperkingen:
    get:
      operationId: GetPubliekrechtelijkeBeperkingen
      description: |
        Zoek publiekrechtelijke beperkingen op een kadastraal onroerende zaak.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/parameters/fields"
        - in: query
          name: kadastraalOnroerendeZaakIdentificatie
          description: |
                        De unieke identificatie van een kadastraal onroerende zaak.
                        Gezocht wordt naar publiekrechtelijke beperkingen die rusten op de onroerende zaak
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHalCollectie"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/406"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Publiekrechtelijke Beperkingen
components:
  schemas:
    PubliekrechtelijkeBeperkingHal:
      allOf:
      - $ref: "domain.yaml#/components/schemas/PubliekrechtelijkeBeperking"
      - properties:
          _links:
            $ref: "#/components/schemas/PubliekrechtelijkeBeperkingLinks"
    PubliekrechtelijkeBeperkingHalCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        _embedded:
          $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHalCollectieEmbedded"
    PubliekrechtelijkeBeperkingHalCollectieEmbedded:
      type: "object"
      properties:
        publiekrechtelijkeBeperkingen:
          type: "array"
          items:
            $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHal"
    PubliekrechtelijkeBeperkingLinks:
      type: "object"
      properties:
        bevoegdGezag:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        stukken:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        stukdelen:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
