---
layout: page-with-side-nav
title: Features
---

# Goals canvas BRK bevragen

## Zoek persoon

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
||||A. zoek persoon|zoeken ingeschreven natuurlijke personen (buiten scope) free query op persoonskenmerken van kadasterNatuurlijkPersoon, KadasterNietNatuurlijkPersoon, IngeschrevenNietNatuurlijkPersoon |kadasterNatuurlijkPersoon, KadasterNietNatuurlijkPersoon, IngeschrevenNietNatuurlijkPersoon  |persoon vinden|[35](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/35){:target="_blank"},[6](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/6){:target="_blank"},[5](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/5){:target="_blank"},[4](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/4){:target="_blank"},[3](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/3){:target="_blank"},[2](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/2){:target="_blank"}|
||"/kadastraalonroerendezaken/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412&typegerechtigde=eigenaar

Via de identificatie van de zakelijkgerechtigde."|kadastrale eigendommen van een persoon vinden |A+1. zoek kadastrale eigendommen van persoon|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie)|kadastraal onroerende zaken  in eigendom van een persoon, inclusief het gezamenlijk aandeel|kadastrale eigendommen van persoon vinden|[83](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/83){:target="_blank"},[72](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/72){:target="_blank"},[61](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/61){:target="_blank"},[35](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/35){:target="_blank"},BUS38,BUS36,BUS17,BUS11,BUS6,[35](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/35){:target="_blank"},[75](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/75){:target="_blank"},[170](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/170){:target="_blank"},[167](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/167){:target="_blank"},[164](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/164){:target="_blank"},BUS12,BUS39|
||"/kadastraalonroerendezaken/?BSN=132451412
/kadastraalonroerendezaken/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412"|alle kadastraal onroerende zaken waarop een persoon een zakelijk recht heeft vinden. |A+2. zoek alle zakelijke rechten van een persoon|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie)|kadastraal onroerende zaken met een zakelijk recht van een persoon, inclusief het gezamenlijk aandeel|zakelijke rechten van persoon vinden|BUS|BUS11,[6](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/6){:target="_blank"},BUS38|
||"/hypotheken/?BSN=132451412&type=geldverstrekker
/hypotheken/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412&type=geldverstrekker"|hypotheken van de geldverstrekker vinden|A+3. zoek hypotheken van de geldverstrekker|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie)|hypotheken van de geldverstrekker |hypotheken van de geldverstrekker vinden|BUS16,[67](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/67){:target="_blank"},BUS9|
||"/hypotheken/?BSN=132451412&type=onderpandgever
/hypotheken/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412&type=onderpandgever"|hypotheken van de onderpandgever vinden (kan kadaster niet leveren)|A+4 zoek hypotheken onderpandgever|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie)|hypotheken van de onderpandgever|hypotheken van de onderpandgever vinden|BUS6|
||"/kadastraalonroerendezaken/?BSN=132451412&typegerechtigde=eigenaar&fields=kadastraleObjectIdentificatie
/kadastraalonroerendezaken/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412&typegerechtigde=eigenaar&fields=kadastraleObjectIdentificatie

Via de identificatie van de zakelijkgerechtigde."|aantal eigendommen van een persoon vinden|A+4 zoek het aantal kadastrale objecten in eigendom van een persoon|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie)|het aantal kadastraal onroerende zaken in eigendom van een persoon, inclusief het gezamenlijk aandeel|aantal kadastrale eigendommen van persoon vinden|[170](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/170){:target="_blank"}|
||"/beslagen/?BSN=132451412&type=beslaglegger
/beslagen/?KadastraalPersoonIdentificatie=NL.IMKAD.PERSOON.132451412&type=beslaglegger"|Zoek beslagleggingen door persoon|A+5 zoek beslagleggingen door persoon|invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie) + periodeVanTotEnMet|kadastraal onroerende zaken waarop beslag is gelegd gedurende de opgegeven periode|beslagleggingen door persoon vinden|[130](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/130){:target="_blank"},[68](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/68){:target="_blank"}|
|||erfpachtscontracten van zakelijk gerechtigde die binnen de opgegeven periode worden beeindigd|A+6 zoek aflopende erfpachtscontracten van persoon (= erfpachtgever) |invoeren identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadasterpersoonIdentificatie) + periodeVanTotEnMet|kadastraal onroerende zaken waarvan het erfpachtcontract eindigt gedurende de opgegeven periode|aflopende erfpachtcontracten|[81](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/81){:target="_blank"}|
||/kadastraalonroerendezakenhistorischevoorkomens?persoon__identificatie|opvragen of een persoon in het verleden koz in eigendom heeft gehad/verkocht|zoek historische zakelijke rechten van een persoon|identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie) evt. aangevuld met periodeVanTotEnMet of peildatum|kadastraal onroerende zaak voorkomens waarin persoon een zakelijk recht heeft (gehad) gedurende de opgegeven periode|opsporing fraude en ondermijning, waarborgen openbare orde en veiligheid, uitvoering WOZ|[73](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/73){:target="_blank"},[74](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/74){:target="_blank"}|BUS38,BUS36|
||/hypothekenhistorischevoorkomens?kadastraalonroerendezaakidentificatie|historische hypotheken van geldverstrekker vinden|zoek historische hypotheken die door geldverstrekker zijn gefinancierd|identificerend kenmerk van een persoon (BSN, KVKnr, RSIN, KadastraalPersoonIdentificatie) evt. aangevuld met periodeVanTotEnMet of peildatum|kadastraal onroerende zaak voorkomens met hypotheken die door persoon zijn gefinancierd|opsporing fraude en ondermijning, waarborgen openbare orde en veiligheid|BUS10,BUS16|

## Zoek Kadastraal Onroerende Zaak

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
||||B. zoek Kadastraal Onroerende Zaak|(zoeken nummeraanduiding, verblijfsobject, ligplaats, standplaats buiten scope) nummeraanduiding, BAGID verblijfsobject, BAGID standplaats, BAGID ligplaats, NIET ADRESSEERBAAR OBJECT, free query op postcode + huisnummer-letter-toevoeging, openbare ruimtenaam huisnummer-letter-toevoeging (fuzzy), kaart (contour, punt) |kadastraal onroerende Zaken |kadastraal onroerende zaak vinden|[34](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/34){:target="_blank"},[38](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/38){:target="_blank"},[7](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/7){:target="_blank"},[1](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/1){:target="_blank"}|
|2|/kadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/zakelijkGerechtigden|zakelijk gerechtigden en hun rechten vinden van een Kadastrale onroerende zaak + aktes|B+1. zoek zakelijk gerechtigden en hun rechten|kadastrale identificatie|zakelijk rechten en de bijbehorende gerechtigden inclusief de stapeling en gezamenlijk aandeel, en de aantekeningen en de erfpachtcanons|zakelijk gerechtigden en hun rechten vinden |BUS32,BUS3,[118](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/118){:target="_blank"},[43](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/43){:target="_blank"},BUS11,BUS1,[127](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/127){:target="_blank"},[78](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/78){:target="_blank"},[44](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/44){:target="_blank"},[28](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/28){:target="_blank"},BUS26,BUS25,BUS4,[80](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/80){:target="_blank"}|
|1|"/kadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/zakelijkGerechtigden?typegerechtigde=""eigenaar"""|eigenaren vinden van een kadastraal onroerende zaak |B+2. zoek eigenaren|kadastrale identificatie|eigenaren Kadastraal Onroerende Zaak en hun aandeel, inclusief het gezamenlijk aandeel |eigenaren vinden van een kadastraal onroerende zaak (inclusief adressen van kadasterpersonen)|[43](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/43){:target="_blank"},[162](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/162){:target="_blank"},[161](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/161){:target="_blank"},[158](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/158){:target="_blank"},[140](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/140){:target="_blank"},[139](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/139){:target="_blank"},[138](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/138){:target="_blank"},[137](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/137){:target="_blank"},[131](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/131){:target="_blank"},[122](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/122){:target="_blank"},[120](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/120){:target="_blank"},[118](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/118){:target="_blank"},[116](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/116){:target="_blank"},BUS35,BUS34,BUS33,BUS31,BUS28,BUS17,BUS11,BUS5,[164](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/164){:target="_blank"},[160](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/160){:target="_blank"},[156](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/156){:target="_blank"},[67](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/67){:target="_blank"},[159](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/159){:target="_blank"},BUS36,BUS30,BUS5,[37](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/37){:target="_blank"},BUS43|
|5|/KadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/hypotheken|hypotheken vinden van kadastraal onroerende zaak en betrokkenen|B+3. zoek zekerheidsstellingen + hypotheeknemer en gever + akte|kadastrale identificatie|zekerheidsstellingen hypothecair + link naar de akte kadastraal onroerende zaken|hypotheken en betrokkenen vinden |[75](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/75){:target="_blank"},BUS6,[67](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/67){:target="_blank"},BUS16,BUS19,BUS40,BUS41|
|3|/KadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}|Eigenschappen raadplegen van KOZ (aanduiding, identificatie, adressen, grenzen, type, kadastrale kaart, coordinaten, oppervlakte, cultuurBebouwdOnbebouwd, koopsom koopjaar)|B+4. raadpleeg eigenschappen KOZ|kadastrale identificatie|eigenschappen|eigenschappen raadplegen|[126](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/126){:target="_blank"},[125](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/125){:target="_blank"},[124](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/124){:target="_blank"},[115](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/115){:target="_blank"},[79](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/79){:target="_blank"},[46](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/46){:target="_blank"},[41](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/41){:target="_blank"},[38](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/38){:target="_blank"},[36](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/36){:target="_blank"},[31](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/31){:target="_blank"},[28](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/28){:target="_blank"},BUS37,BUS23,BUS42|
|4|"/KadastraalOnroerendeZaken/{KadastraalObjectIdentificatie}/ZakelijkGerechtigden/aktes"|aktes van KOZ vinden en inzien |raadpleeg documenten|kadastrale identificatie|stukken van zakelijk gerechtigden link naar document |aktes vinden van een kadastraal roerende zaak |[135](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/135){:target="_blank"},[32](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/32){:target="_blank"},[29](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/29){:target="_blank"},BUS26,BUS20,BUS16/hypotheek|BUS15 makelaar|BUS14|
||/publiekrechtelijkebeperkingen/|publiekrechtelijke beperkingen vinden en inzien|B+6. raadpleeg publiekrechtelijke beperkingen |PRBidentificatie |publiekrechtelijke beperkingen + stuk|publiekrechtelijke beperkingen vinden van een kadastraal roerende zaak +stuk|[133](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/133){:target="_blank"},[78](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/78){:target="_blank"},[66](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/66){:target="_blank"},BUS18|
|6|"/KadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/PrivaatrechtelijkeBeperkingen"|privaatrechtelijke beperkingen vinden en inzien|B+7. raadpleeg privaatrechtelijke beperkingen |kadastrale identificatie|kadastraal onroerende zaak met privaatrechtelijke beperkingen en  stuk|privaatrechtelijke beperkingen met stukken vinden van een kadastraal roerende zaak|[132](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/132){:target="_blank"},[78](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/78){:target="_blank"},[66](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/66){:target="_blank"},BUS18|
|7|"/KadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/beslagleggingen
/KadastraalOnroerendeZaken/{kadastraalObjectIdentificatie}/beslagleggingen/aktes"|beslagleggingen vinden en inzien|B+8. raadpleeg beslagleggingen|kadastrale identificatie|kadastraal onroerende zaken met beslagleggingen en stuk|beslagleggingen met stukken vinden|[68](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/68){:target="_blank"},BUS18,BUS7|
|8|Kan ook met contour!|aangrenzende percelen vinden en inzien|raadpleeg aangrenzende percelen + appartmentsrechten|invoeren kadastrale identificatie|aangrenzende percelen + appartementsrechten|aangrenzende percelen + appartementsrechten vinden|[160](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/160){:target="_blank"},[116](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/116){:target="_blank"},[79](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/79){:target="_blank"}|
||/kadastraalonroerendezakenhistorischevoorkomens/{kadastraalonroerendezaakidentificatie}?datumVan&datumTotEnMet|Alle eigenschappen (koopsommen, grenzen, splitsingen en samenvoegingen etc.) en zakelijk gerechtigden + koopaktes opvragen van een (historische) kadastraal onroerende zaak op een datum in het verleden of binnen een periode.|eigenschappen, aktes en zakelijk gerechtigden vinden van een KOZ op periode of peildatum|kadastrale indentificatie  met periode |voorkomens van (historische) kadastraal onroerende zaak met zakelijk gerechtigden en stukken (BLOB)|WOZ/ belastingzaken, opsporing fraude en ondermijning, waarborgen openbare orde en veiligheid, |[453](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/453){:target="_blank"},[45](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/45){:target="_blank"},[42](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/42){:target="_blank"},[33](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/33){:target="_blank"},[29](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/29){:target="_blank"}|BUS13,BUS19,BUS8,BUS22,BUS21,BUS27,BUS14,BUS24,BUS43,BUS20||||||||||||||||||||||
||/kadastraalonroerendezakenhistorischevoorkomens/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen?datumVan&datumTotEnMet|privaatrechtelijke beperkingen  opvragen van een (historische) kadastraal onroerende zaak op een datum in het verleden of binnen een periode.|privaatrechtelijke beperkingen vinden van een KOZ op periode of peildatum|kadastrale indentificatie  met periode |voorkomens van (historische) kadastraal onroerende zaak met privaatrechtelijke beperkingen en stukken |Controles en verbeteringen WOZ admi en het behandelen van bezwaar en beroep|[616](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/616){:target="_blank"}|
||/publiekrechtelijkebeperkingenhistorischevoorkomens?kadastraalOnroerendeZaakIdentificatie&datumVan&datumTotEnMet|publiekrechtelijke beperkingen  opvragen van een (historische) kadastraal onroerende zaak op een datum in het verleden of binnen een periode.|publiekrechtelijke beperkingen vinden van een KOZ op periode of peildatum|kadastrale indentificatie  met periode |voorkomens van (historische) publiekrechtelijke beperkingen (inclusief stukken en relaties naar voorkomens van KOZen)  |Controles en verbeteringen WOZ admi en het behandelen van bezwaar en beroep|[617](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/617){:target="_blank"}|
||Toevoegen properties datumvan en datumTotEnMet|||||||

## Zoek Kadastraal roerende Zaak

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
||||C. zoek Kadastraal roerende Zaak|invoeren nummeraanduiding, free query op postcode + huisnummer-letter-toevoeging, openbare ruimtenaam huisnummer-letter-toevoeging (fuzzy), kaart (contour, punt) |kadastraal roerende zaken|kadastraal roerende zaken vinden||
|||eigenaren vinden van een woonschip of woonwagen|C+1. zoek eigenaren van KOZ|invoeren kadastrale identificatie|eigenaren Kadastraal roerende zaak|eigenaren vinden van een woonschip/woonwagen|[119](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/119){:target="_blank"},[72](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/72){:target="_blank"},[73](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/73){:target="_blank"},BUS3,BUS1,BUS12,BUS10,[77](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/77){:target="_blank"},BUS2|
|||zakelijk gerechtigden vinden van woonschip of woonwagen|C+2. zoek zakelijk gerechtigden van KOZ|invoeren kadastrale identificatie|zakelijk gerechtigden Kadastraal roerende zaak|zakelijk gerechtigden kadastraal onroerende zaak|BUS1,BUS2|
|||zekerheidsstellingen vinden van kadastraal roerende zaak (woonschip of woonwagen, vliegtuigen en boten)|C+3. zoek zekerheidsstellingen (+ hypotheekverstrekker + stukdeel) van KOZ|invoeren kadastrale identificatie |zekerheidsstellingen (hypotheekverstrekker + stukdeel) kadastraal roerende zaken |zekerheidsstellingen vinden van een kadastraal roerende zaak |[75](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/75){:target="_blank"},BUS6,BUS10|

## Zoek het eigendomsrecht en de tenaamstelling van Kadastraal Onroerende Zaken in een Pand

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
|||alle eigenaren van kadastraal onroerende zaken in een pand vinden|D. zoek het eigendomsrecht en de tenaamstelling van Kadastraal Onroerende Zaken in een Pand|invoeren BAGID Pand|eigenaren kadastraal Onroerende Zaken (perceel, appartmentsrecht, verblijfsobject, berging of parkeergarage) |eigenaren vinden van alle kadastraal onroerende zaken in een pand (perceel, appartmentsrecht, verblijfsobject, berging of parkeergarage) |[82](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/82){:target="_blank"},[158](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/158){:target="_blank"},[122](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/122){:target="_blank"},[83](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/83){:target="_blank"},[77](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/77){:target="_blank"},[49](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/49){:target="_blank"}|

## Zoek het eigendomsrecht en de tenaamstelling van Kadastraal Onroerende Zaken in een Gebied

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
|||alle eigenaren van kadastraal onroerende zaken in een gebied vinden|"E. zoek het eigendomsrecht en de tenaamstelling van Kadastraal Onroerende Zaken in een Gebied
 (eerst via de locatieserver wordt op basis van de contour een collectie KOZ-id's opgehaald en die zijn input voor de bevraging. )"|invoeren contour|eigenaren kadastraal Onroerende Zaken|eigenaren vinden van alle kadastraal onroerende zaken in een gebied|[171](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/171){:target="_blank"},[155](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/155){:target="_blank"},[165](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/165){:target="_blank"},[136](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/136){:target="_blank"},[77](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/77){:target="_blank"}|

## Zoek de VVE's in een Pand|invoeren BAGID Pand

| PRIO|   |WHATS|HOWS|INPUT|OUTPUT|GOALS|STORIES|
|---  |---|---  |--- |---  |---   |---  |---    |
|||alle VVE's van een pand vinden|F. zoek de VVE's in een Pand|invoeren BAGID Pand|VVE's Pand|VVE's vinden van een pand|[123](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/123){:target="_blank"},[69](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/69){:target="_blank"}|
