svcutil /noconfig /syncOnly /serializable /out:DataTypes.cs ^
	KadastraleOnroerendeZaak.wsdl ^
	StUF4_ent_adressengebouwen.xsd ^
	StUF4_msg_adressengebouwen.xsd ^
	StUF4_msg_gemeenschappelijk.xsd ^
	StUF4_ent_gemeenschappelijk.xsd ^
	StUF4_msg_buurt.xsd ^
	StUF4_ent_buurt.xsd ^
	StUF4_msg_ingeschrevennietnatuurlijkpersoon.xsd ^
	StUF4_ent_nietnatuurlijkpersoon.xsd ^
	StUF4_msg_ingeschrevenpersoon.xsd ^
	StUF4_ent_ingeschrevenpersoon.xsd ^
	StUF4_ent_natuurlijkpersoon.xsd ^
	StUF4_msg_kadastraleonroerendezaak.xsd ^
	StUF4_ent_kadastraleonroerendezaak.xsd ^
	StUF4_msg_maatschappelijkeactiviteit.xsd ^
	StUF4_ent_handelsregister.xsd ^
	StUF4_msg_vestiging.xsd ^
	StUF4_ent_wijk.xsd ^
	StUF4_msg_wijk.xsd ^
	StUF4_ent_extern_geometrie.xsd ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Extern/Entiteiten/Geometrie,StUF4.Extern.Entiteiten.Geometrie ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/Gemeenschappelijk,StUF4.Entiteiten.Gemeenschappelijk ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/Gemeenschappelijk,StUF4.Koppelvlak.Services.Gemeenschappelijk ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/AdressenEnGebouwen,StUF4.Entiteiten.AdressenEnGebouwen ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/AdressenEnGebouwen,StUF4.Koppelvlak.Services.AdressenEnGebouwen ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/NietNatuurlijkPersoon,StUF4.Entiteiten.NietNatuurlijkPersoon ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/IngeschrevenNietNatuurlijkPersoon,StUF4.Koppelvlak.Services.NietNatuurlijkPersoon ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/IngeschrevenPersoon,StUF4.Koppelvlak.Services.NatuurlijkPersoon ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/NatuurlijkPersoon,StUF4.Entiteiten.NatuurlijkPersoon ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/IngeschrevenPersoon,StUF4.Entiteiten.IngeschrevenPersoon ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/KadastraleOnroerendeZaak,StUF4.Koppelvlak.Services.KadastraleOnroerendeZaak ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/KadastraleOnroerendeZaak,StUF4.Entiteiten.KadastraleOnroerendeZaak ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/Handelsregister,StUF4.Entiteiten.Handelsregister ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/MaatschappelijkeActiviteit,StUF4.Koppelvlak.Services.MaatschappelijkeActiviteit ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/Vestiging,StUF4.Koppelvlak.Services.Vestiging ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/Buurt,StUF4.Entiteiten.Buurt ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/Buurt,StUF4.Koppelvlak.Services.Buurt ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Entiteiten/Wijk,StUF4.Entiteiten.Wijk ^
	/n:http://www.stufstandaarden.nl/koppelvlak/STUF4/Berichten/Wijk/v4,StUF4.Koppelvlak.Services.Wijk

